# Generated by Django 4.1.1 on 2022-11-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='N/A', max_length=250)),
                ('nombre', models.CharField(default='Sin nombre', max_length=250)),
                ('nivelOD', models.FloatField(default=0)),
                ('nivelORP', models.FloatField(default=0)),
                ('estadoORP', models.CharField(default='N/A', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Aireador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.FloatField(default=0)),
                ('consumoActual', models.FloatField(default=0)),
                ('fechaUltimaPausa', models.DateField(auto_now=True)),
                ('isOn', models.BooleanField(default=False)),
                ('laguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piscinas.laguna')),
            ],
        ),
    ]
