# Generated by Django 4.1.1 on 2022-11-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laguna',
            name='estadoOD',
            field=models.CharField(default='N/A', max_length=250),
        ),
    ]
